# Generated by Django 4.1.4 on 2022-12-23 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='data',
            new_name='date',
        ),
    ]
